apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cilium
  namespace: flux-system
  labels:
    cluster-layer: "1"
spec:
  releaseName: cilium
  targetNamespace: network-system
  interval: 24h
  chart:
    spec:
      chart: chart/common/external/cilium
      version: "1.17.3"
      interval: 9999h0m
      sourceRef:
        kind: HelmRepository
        name: registry-local
        namespace: flux-system
  upgrade:
    remediation:
      remediateLastFailure: true
  values:
    kubeProxyReplacement: true
    k8sServiceHost: 10.6.31.30
    k8sServicePort: 6443
    ipam:
      operator:
        clusterPoolIPv4PodCIDRList: ["10.252.0.0/20"]
        clusterPoolIPv4MaskSize: 20
    l2announcements:
      enabled: true
    externalIPs:
      enabled: true
    operator:
      replicas: 1
