apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: topolvm
  namespace: flux-system
  labels:
    cluster-layer: "1"
spec:
  releaseName: topolvm
  targetNamespace: storage-system
  interval: 24h
  chart:
    spec:
      chart: chart/common/external/topolvm
      version: "15.5.4"
      interval: 9999h0m
      sourceRef:
        kind: HelmRepository
        name: registry-local
        namespace: flux-system
  upgrade:
    remediation:
      remediateLastFailure: true
  values:
    lvmd:
      deviceClasses:
        - name: thin
          volume-group: topolvm
          type: thin
          thin-pool:
            name: "pool0"
            overprovision-ratio: 5.0
    storageClasses:
      - name: topolvm
        storageClass:
          fsType: xfs
          reclaimPolicy: Delete
          isDefaultClass: true
          volumeBindingMode: WaitForFirstConsumer
          allowVolumeExpansion: true
          additionalParameters:
            '{{ include "topolvm.pluginName" . }}/device-class': "thin"
    controller:
      replicaCount: 1
    cert-manager:
      enabled: true
    snapshot:
      enabled: true
