apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tekton-operator
  namespace: flux-system
  labels:
    cluster-layer: "0"
spec:
  releaseName: tekton-operator
  targetNamespace: tekton-operator
  interval: 5m
  chart:
    spec:
      chart: chart/common/external/tekton-operator
      version: "0.75.0"
      interval: 9999h0m
      sourceRef:
        kind: HelmRepository
        name: registry-local
        namespace: flux-system
  upgrade:
    remediation:
      remediateLastFailure: true
  values:
    installCRDs: true
    controllers: "tektonconfig,tektonpipeline,tektondashboard"
