---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: automation-task
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: ${repository__branch}
  secretRef:
    name: git-cred
  url: ${repository__baseUrl}/automation/task
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-automation
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-layer-1
  interval: 10m0s
  path: ./
  prune: true
  sourceRef:
    kind: GitRepository
    name: automation-task

