apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-layer-1
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-layer-0
  interval: 10m0s
  path: ./cluster-layer-1
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: cluster-local
  postBuild:
    substituteFrom:
      - kind: Secret
        name: flux-variables

