apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-layer-2
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-layer-1
  interval: 10m0s
  path: ./cluster-layer-2
  prune: true
  commonMetadata:
    labels:
      cluster-layer: "2"
  sourceRef:
    kind: GitRepository
    name: cluster-local
  postBuild:
    substituteFrom:
      - kind: Secret
        name: flux-variables

