apiVersion: v1
kind: Namespace
metadata:
  name: source-system
---
apiVersion: v1
kind: Namespace
metadata:
  name: network-system
---
apiVersion: v1
kind: Namespace
metadata:
  name: storage-system
---
apiVersion: v1
kind: Namespace
metadata:
  name: tekton-operator
---
apiVersion: v1
kind: Namespace
metadata:
  name: tekton-pipelines
---
apiVersion: v1
kind: Namespace
metadata:
  name: tekton-runs
---
apiVersion: v1
kind: Namespace
metadata:
  name: pki-system
