apiVersion: v1
kind: Namespace
metadata:
  name: tekton-operator
---
apiVersion: v1
kind: Namespace
metadata:
  name: tekton-pipelines
--- 
apiVersion: v1
kind: Namespace
metadata:
  name: tekton-run
 
