fluxVariables:
  repositoryBaseUrl: 
  repositoryBranch: 
  repositorySshIdentityB64: 
  repositorySshKnownHosts: 

#additionalFluxVariables: |-
#  key: value

kubeadmConfig: 
  k8sVersion:
  initHostIP:
  apiFQDN:
  podSubnet:
  serviceSubnet:
