apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: registry
  namespace: source-system
spec:
  dnsNames:
  - registry
  - registry.source-system
  duration: 8760h
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: cluster-ca
  secretName: registry-tls
  privateKey:
    rotationPolicy: Always
  usages:
  - digital signature
  - key encipherment
  - server auth
  - client auth
