apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: build-image
  namespace: tekton-runs
spec:
  params:
    - name: repository
      type: string
    - name: registry
      type: string
  steps:
    - name: build-img
      image: gcr.io/kaniko-project/executor:v1.21.0
      args:
        - --context
        - /workspace
        - --dockerfile
        - Dockerfile
        - --skip-tls-verify
        - --insecure-registry
        - trow.melon.local
        - --destination
        - trow.melon.local/melonflix2:2.0.1
      env:
        - name: REPOSITORY
          value: $(params.repository)
        - name: REGISTRY
          value: $(params.registry)
        - name: CLUSTERCACERT
          valueFrom:
            secretKeyRef:
              key: ca.crt
              name: registry-local-ca
        - name: REGUSER
          valueFrom:
            secretKeyRef:
              key: username
              name: registry-local-cred
        - name: REGPASS
          valueFrom:
            secretKeyRef:
              key: password
              name: registry-local-cred
  workspaces:
    - name: workspace
      mountPath: /workspace
