apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: build-image
  namespace: tekton-runs
spec:
  params:
    - name: repository
      type: string
    - name: revision
      type: string
    - name: registry
      type: string
  stepTemplate:
      securityContext:
        privileged: true
        seccompProfile:
          type: Unconfined
        #appAromorProfile:
        #  type: Unconfined
        runAsUser: 1000
        runAsGroup: 1000
  steps:
    - name: build-img
      image: moby/buildkit:v0.21.0-rootless
      script: |
        cd /workspace
        REPO_PATH=${REPOSITORY#*git/}
        for DOCKERFILE in `find . -type f -name Dockerfile`
        do
            echo " + Dockerfile found: $DOCKERFILE"
            CONTEXT=$(dirname $DOCKERFILE)
            NAME="$(awk '$1 ~ /#--name/ {print $2}' $DOCKERFILE)"
            if [[ -z $NAME ]]
            then
                IMGNAME=$REGISTRY/$REPO_PATH:$IMGTAG
            else
                IMGNAME=$REGISTRY/$REPO_PATH-$NAME:$IMGTAG
            fi
            buildctl-daemonless.sh build \
              --frontend dockerfile.v0 \
              --local context=$CONTEXT \
              --local dockerfile=$CONTEXT \
              --output type=image,oci-mediatypes=true,name=$IMGNAME,push=true,registry.insecure=true
        done
      env:
        - name: REPOSITORY
          value: $(params.repository)
        - name: REGISTRY
          value: $(params.registry)
        - name: IMGTAG
          value: $(params.revision)
        - name: BUILDKITD_FLAGS
          value: --oci-worker-no-process-sandbox
  workspaces:
    - name: workspace
      mountPath: /workspace
