apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: get-git
  namespace: tekton-runs
spec:
  params:
    - name: repository
      type: string
    - name: revision
      type: string
  steps:
    - name: get-git
      image: alpine/git
      script: |
        cd /workspace
        git init -b workspace
        git pull --depth=1 $(params.repository) $(params.revision)
      volumeMounts:
        - name: git
          mountPath: /var/lib/git
  volumes:
     - name: git
       hostPath:
         path: /var/lib/git
         type: Directory
  workspaces:
    - name: workspace
      mountPath: /workspace
