apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: push-chart
  namespace: tekton-runs
spec:
  params:
    - name: repository
      type: string
    - name: registry
      type: string
  steps:
    - name: push-chart
      image: alpine/helm:3.17.3
      script: |
        cd /workspace
        REG_PATH=${REPOSITORY#*git/}

        CHART=$(dirname `find . -type f -name Chart.yaml -exec dirname {} \;`)
        echo " + Helm Chart found: $CHART"
        helm package $CHART

        helm push $NAME-* oci://$REGISTRY/chart/${REG_PATH%/*}
      env:
        - name: REPOSITORY
          value: $(params.repository)
        - name: REGISTRY
          value: $(params.registry)
  workspaces:
    - name: workspace
      mountPath: /workspace

