apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: push-chart
  namespace: tekton-runs
spec:
  params:
    - name: repository
      type: string
    - name: registry
      type: string
  steps:
    - name: push-chart
      image: alpine/helm:3.17.2
      script: |
        cd /workspace
        REPO_PATH=${REPOSITORY#*git/}
        REPO_NAME=${REPO_PATH##*/}
        CHART=$(find . -type f -name Chart.yaml -exec dirname {} \;)
        CHART_NAME="$(awk '$1 ~ /name:/ {print $2}' $CHART/Chart.yaml)"
        echo " + Helm Chart '$CHART_NAME' found: $CHART"
        helm package $CHART
        if [[ $REPO_NAME == $CHART_NAME ]]
        then
            helm push $CHART_NAME-* oci://$REGISTRY/chart/${REPO_PATH%/*} --plain-http
        else
            helm push $CHART_NAME-* oci://$REGISTRY/chart/${REPO_PATH}/${CHART_NAME} --plain-http
        fi
      env:
        - name: REPOSITORY
          value: $(params.repository)
        - name: REGISTRY
          value: $(params.registry)
  workspaces:
    - name: workspace
      mountPath: /workspace
