apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: upgrade-chart
  namespace: tekton-runs
spec:
  params:
    - name: target
      type: string
      description: 'Helm release to upgrade in <namespace>/<release> format'
    - name: revision
      type: string
      description: 'Commit SHA or tag'
  steps:
    - name: upgrade-chart
      image: alpine/helm:3.17.2
      script: |
        cd /workspace
        CHART=$(find . -type f -name Chart.yaml -exec dirname {} \;)
        NS=${TARGET%/*}
        RELEASE=${TARGET#*/}
        echo " + Upgrading '$RELEASE' in '$NS'"
        helm upgrade $RELEASE $CHART -n $NS --reuse-values --set image.tag=$IMGTAG
      env:
        - name: TARGET
          value: $(params.target)
        - name: IMGTAG
          value: $(params.revision)
  workspaces:
    - name: workspace
      mountPath: /workspace
